/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ParallaxScript")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class ParallaxScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "583158cfb56d7e24bb178a5dd0db6cde";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_Cam = default;
        [SerializeField] public UnityEngine.Vector2 m_parallaxFactor = new Vector2(0, 0);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Cam),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_parallaxFactor),
            };
        }
    }
}

#endif
