/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlatformerCamera")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PlatformerCamera : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "1db951a1896a94944ae6874879c3cb8f";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Zoom Settings")]
        [SerializeField] public System.Double m_zoom = 15;
        [SerializeField] public System.Double m_zoomMin = 10;
        [SerializeField] public System.Double m_zoomMax = 50;
        [SerializeField] public System.Double m_cameraFollowSpeed = 2;
        [SerializeField] public System.Double m_xOffset = 0;
        [SerializeField] public System.Double m_yOffset = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_zoom),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_zoomMin),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_zoomMax),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_cameraFollowSpeed),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_xOffset),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_yOffset),
            };
        }
    }
}

#endif
